{% set name = "brotli-asgi" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f9985d99ecb082cf5e67486a58c27b7f39b2d3be8d9d13c38abc12328cedce9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - brotli-python >=1.0.9
    - pip
    - python >=3.7
    - starlette >=0.25.0
  run:
    - brotli-python >=1.0.9
    - python >=3.7
    - starlette >=0.25.0

test:
  imports:
    - brotli_asgi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fullonic/brotli-asgi
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A compression AGSI middleware using brotli

extra:
  recipe-maintainers:
    - fullonic
    - dcfidalgo
