{% set name = "brotli-asgi" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e7160a3a86f22659e9d978829f46615914cdd6c7fd04054f4050a2ec78da79c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - brotli-python >=1.0.7
    - pip
    - python >=3.6
    - starlette >=0.13.4
  run:
    - brotli-python >=1.0.7
    - python >=3.6
    - starlette >=0.13.4

test:
  imports:
    - brotli_asgi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fullonic/brotli-asgi
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A compression AGSI middleware using brotli

extra:
  recipe-maintainers:
    - fullonic
    - dcfidalgo
